### ISSUE TITLE
Todoist Tasks Imported as 1 Day After Task Date

### ISSUE THREAD

**Issue by seesemichaelj** [KinToday/kin-web-client#27]
When Todoist tasks are imported, they are assigned in Kin the day after they exist in Todoist.

**Comment by seesemichaelj** [comment]
Quote from @zowesiouff on this issue "Yep, I haven't had time to dig again on this issue. From my last deep dive, Todoist seems to offset the dates in its UI by the timezone used in their settings, which yields some funny results in Kin, because we expect providers to give us the "absolute" dates ( with tz data ) when we ask for events. Hopefully, I'll be able to fix this soon-ish."

**Comment by CarJem** [comment]
Is this ever going to get fixed, or is there a problem?

**Comment by arbourd** [comment]
This issue is probably more related to the backend then the frontend. The client just gets `date` which is wrong.

**Comment by zowesiouff** [comment]
@CarJem @arbourd @seesemichaelj closing this, it's been fixed and deployed to `kin.today`. Feel free to reopen if we missed something.

**Comment by chispito** [comment]
Keeps happening...just created a todo and it moves it to the following day...please fix, it's quite annoying! Thanks!

**Comment by zowesiouff** [comment]
You need to give us more details here ... as you probably have guessed by now, this is super finicky.

Did you create the todo in Kin? in Todoist? Do you have the same timezone used in both applications? What's your timezone? Are your other todos properly placed?

If you don't want to share those details publicly, you can reach out to us at hello at kin dot today

Without more information, there is nothing we can do.

**Comment by chispito** [comment]
I created the todo in Kin, I'm in Madrid and have timezones OK. If I create it it in Todoist, it shows OK in Kin...

**Comment by zowesiouff** [comment]
In theory it should be fixed :)

**Comment by chispito** [comment]
Cool!! Working now!!! Many thanks!!! That was fast!! 👍
