### ISSUE TITLE
Incorrect defaults

### ISSUE THREAD

**Issue by jason-feng** [KinToday/kin-web-client#32]
Although my default calendar is set to gmail, Kin creates new events under wunderlist

**Comment by zowesiouff** [comment]
Is your "default" calendar loaded/displayed in your Kin account? If not, Kin will default to the first usable (as in loaded) calendar.

it's an unintuitive issue we have right now (same as not being able to create an event in an "unloaded" calendar).

**Comment by jason-feng** [comment]
yes it is loaded

**Comment by zowesiouff** [comment]
Just to clarify the vocabulary used:
![screen shot 2017-06-06 at 21 08 17](https://user-images.githubusercontent.com/12000287/26847149-4a6ee5cc-4afc-11e7-969f-d9e8bfc6e39a.png)
Here I've a Google account connected, "test 01" is loaded, "test 02" isn't. If "test 02" was my default calendar and I created a new event, Kin would create it on "test 01".

**Comment by jason-feng** [comment]
Yup i have it set to my personal gmail and its loaded
