### ISSUE TITLE
Todoist Calendar Entries cannot be edited to be shorter than 1 hour

### ISSUE THREAD

**Issue by hughwphamill** [KinToday/kin-web-client#37]
Create a task in Todoist.

Assign time to task in Kin

Change duration to 15 minutes by editing end time

Expected Result: Entry is 15 minutes in duration

Actual Result: End time changes to make entry 1 hour in duration

**Comment by hughwphamill** [comment]
Just noticed you also can't make them longer than one hour.

**Comment by zowesiouff** [comment]
@hughwphamill For now, we try to keep as much data as possible in the respective providers. This means we (mostly) cannot extend the functionalities of each provider. AFAIK, Todoist doesn't have the concept of a duration or an end date. This means any event imported from Todoist will either be:
- an all-day event with a default duration of 1day.
- a timed event with a default duration of 1h.

We could start saving a duration or an end date in KIn, but it means having a far more resilient data storage to make sure we're not loosing any important data and we're not considering exploring this at this point, I'll close this for now.

**Comment by hughwphamill** [comment]
@zowesiouff Thanks for the reply! I totally understand about not wanting to maintain state outside of the source system, makes sense.

I wonder if it would be useful functionality to duplicate and/or move an event from one source system to another, for instance, create a google calendar item for a todoist item. I'd be happy to have the todoist item in there as an all day event and easily create a google item to schedule it.
