### ISSUE TITLE
Internal server error when adding O365 account

### ISSUE THREAD

**Issue by terodev** [KinToday/kin-web-client#45]
I have tried a couple of times to add an O365 account, but it fails with an error message of "Internal server error, please retry later".

Could this be related to deleted OAuth application like in a previous issue https://github.com/KinToday/kin-web-client/issues/43?

**Comment by zowesiouff** [comment]
Hi @ripatte, sorry for the delay here

Sadly, I couldn't find anything in our logs to understand what happened. Are you still experiencing this issue? Would you mind sharing with us a bit more about the account that's causing you issue [0]? You can reach us at hello at kin dot today if you don't want to post that publicly ;) 

[0] Outlook / O365 / Microsoft are supposed to be accessible from the same API now but considering how long it took them to go through that "migration", I suppose there are still some rough edge cases that aren't ironed out for some accounts :(

**Comment by ripatte** [comment]
The issue persists. I'll send you an email with the account details :)

**Comment by ripatte** [comment]
@zowesiouff, I sent you an email yesterday with more details
