### ISSUE TITLE
Setup guide improvements

### ISSUE THREAD

**Issue by sqbiz** [KinToday/kin-web-client#9]
I'm looking forward to taking a look at Kin! I started setting things up but the documentation is a little unclear. I've spent 45 minutes or so getting it all rolling, and still wasn't able to get everything set up. I'm sure with some more time I'd be able to figure it out, but, as someone who's setting this up just to take a look at what Kin is and how it works (I was late to sign up for the invite), it's all of the time I'm able to spend on getting it working right now.

For instance, with some of the OAauth client ID configurations:

    /*
     * Google OAuth app secrets
     * https://console.developers.google.com/projectselector/apis/credentials
     */
    GOOGLE_CLIENT_ID: '',
    GOOGLE_CLIENT_SECRET: '',
    GOOGLE_MAPS_KEY: '',

There are a handful of different Google Maps APIs, it's not clear which one needs to be turned on.

Also:
 - The eventbrite "ID" is called the "App Key"
 - I didn't see any Internal ID when I created my Meetup key.

A couple more lines on each of these to describe the steps would be helpful.

Also, on a somewhat separate note, I noticed that if I wasn't providing keys for all of the different OAuth services, the API was continuously crashing.

**Comment by zowesiouff** [comment]
I've added more comments / explanations in `secrets.js` in [0614482](https://github.com/KinToday/kin-api-server/commit/061448226b1d36e3b315af0c3ca36b2487b9b09b) to not have to search the answer on this issue ;) 

> There are a handful of different Google Maps APIs, it's not clear which one needs to be turned on.

Yep definitely, the one we use currently is the Google Static Map API, it's not great but it's easy to setup, there will most likely be a migration further down the line as we can't detect whether a location is found before displaying the "map" to the user.

> The eventbrite "ID" is called the "App Key"

Yeah, OAuth2 is great ... except all those providers implement it in a slightly different way, with slightly different names and slightly different behaviours :) Anyhow, the "translation" is now documented in the file.

> I didn't see any Internal ID when I created my Meetup key.

That internal ID is a weird beast, we're currently only using it when someone deauth Meetup from Kin: it's one of the only provider that allows us to craft a query to deauth the app. That said, they "allow" it in a way that just isn't practical (and isn't secure)

> Also, on a somewhat separate note, I noticed that if I wasn't providing keys for all of the different OAuth services, the API was continuously crashing.

I had written a blurb about that on another issue: [kin-api-server/issues/16](https://github.com/KinToday/kin-api-server/issues/16): 

> In theory, providers are disabled by default until you set values for their various secrets. You will be greeted by messages like this in the logs when starting the server or each unconfigured provider:
WARN could not load file auth.js for source github: TypeError: OAuth2Strategy requires a clientID option
(in this case we have no client ID / client secret for Github)
... except for Facebook and Google. They are used as an authentication mechanism to connect to Kin, and we haven't had time to make them by-passable if not configured.

I've now directly added it in `secrets.js` for easier access ;) 

Thanks again, and keep the feedback coming, it's highly appreciated.

I'm closing this for now but feel free to reopen if you find any other quirks needing more documentation / explanation.
